#3. Algoritmo para trocar o pneu do carro (Imprimir a sequência para trocar o pneu do carro)

print("01. Verificar onde está guardado o macaco no carro")
print("02. Verificar onde está guardada a chave de roda no carro")
print("03. Verificar onde está guardado o step no carro")
print("04. Pegar as duas ferramentas, o step e ir até o pneu")
print("05. Posicionar o macaco na estrutura fixa do carro")
print("06. Utilizar a alavanca do macaco para suspender o carro e deixar o pneu livre")
print("07. Com a chave de roda, soltar os 4 parafusos que prendem a roda")
print("08. Retirar o pneu furado")
print("09. Posicionar o step no lugar")
print("10. Prendê-lo com os 4 parafusos utilizando a chave de roda")
print("11. Soltar a alavanca do macaco")
print("12. Recolher a chave de roda, o macaco e o pneu furado")
print("13. Guardá-los no porta-malas")